# Generated by Django 4.1.4 on 2022-12-28 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B_post',
            fields=[
                ('post_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('b_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_users.b_user')),
            ],
            options={
                'db_table': 'blog_posts',
            },
        ),
    ]
