# Generated by Django 4.1.3 on 2022-11-30 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b_users', '0001_initial'),
        ('b_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B_view',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('b_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_posts.b_post')),
                ('b_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_users.b_user')),
            ],
            options={
                'db_table': 'view',
            },
        ),
    ]
