# Generated by Django 4.1.3 on 2022-11-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_views', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='b_view',
            table='blog_view',
        ),
    ]
