# Generated by Django 4.1.4 on 2022-12-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_showtime',
            fields=[
                ('showtime_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'movie_showtimes',
            },
        ),
    ]
